#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Domotica.Resource", IsApplication=true)]

namespace Domotica
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int Icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int abort = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int buttonChangePinState = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int buttonConnect = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int editTextIPAddress = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int editTextIPPort = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int exit = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int relativeLayout1 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int seekBar1 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int textViewChangePinState = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int textViewChangePinStateValue = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int textViewDebug = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int textViewDebugValue = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int textViewIPAddress = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int textViewIPPort = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int textViewSensor = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int textViewSensorValue = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int textViewServer = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int textViewServerConnect = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int textViewTimerState = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int textViewTimerStateValue = 2130837523;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F040000
			public const int menu = 2130968576;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int abort = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int application_name = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int arduino_server_connect = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int arduino_server_text = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int button_connect_text = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int button_pin_state_text = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int change_pin_state_value = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int debug_text = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int debug_value = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int exit = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int ip_address_text = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int ip_address_value = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int ip_port_text = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int ip_port_value = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int pin_state_text = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int sensor_text = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int sensor_value = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int timer_state_text = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int timer_state_value = 2131034130;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
